logging:
    level:
        ROOT: ERROR
        io:
            reactivestax: DEBUG
        org:
            springframework: ERROR
            springframework.boot.context.config: DEBUG
            springframework.security: TRACE
            springframework.web: TRACE
pattern:
    console: '%d %-5level %logger : %msg%n'
server:
    port: 8888
spring:
    resource-uri: http://localhost:8080/time
    security:
        oauth2:
            client:
                registration:
                    auth0:
                        client-name: okta-auth-code
                        client-id: cWvSGEi4Nn16nAmVa9ylNycE59XOmU5h
                        client-secret: MjL8B6NtiJIRo4ofNQfwCI54HKQt8qU3ZlLkynKhQ7t9NYe9PI0q5LuF2Ni8rXHb
                        scope:
                            - openid
                            - offline_access
                        authorization-grant-type: authorization_code
                        redirect-uri: https://localhost:8888/login/oauth2/code/auth0
                provider:
                    auth0:
                        issuer-uri: "https://dev-u14yaemx.us.auth0.com/"

server.ssl.key-store: classpath:jks/server-keystore.jks
server.ssl.key-store-password: server-store-pass
server.ssl.key-alias: server-keypair
server.ssl.key-password: server-key-pass