logging:
    level:
        ROOT: ERROR
        io:
            reactivestax: DEBUG
        org:
            springframework: ERROR
            springframework.boot.context.config: DEBUG
            springframework.security: TRACE
            springframework.web: TRACE
pattern:
    console: '%d %-5level %logger : %msg%n'
server:
    port: 8888
spring:
    resource-uri: http://localhost:8080/time
    security:
        oauth2:
            client:
                registration:
                    okta:
                        client-name: okta-auth-code
                        client-id: K9TjqgDF6sqLAtn0M3R5j1aoYkLIHsWm
                        client-secret: 4Aj_SOWVSD9UyBX1VxIN9i-x6e47sNp8QQfFIKUy1wThcK_kxV6bZG2MvhxOpUjl
                        scope:
                            - openid
                            - offline_access
                            - accesstime-consent-req
                        authorization-grant-type: authorization_code
                        redirect-uri: https://localhost:8888/login/oauth2/code/auth0
                provider:
                    okta:
                        issuer-uri: "https://dev-u14yaemx.us.auth0.com/"

server.ssl.key-store: classpath:jks/server-keystore.jks
server.ssl.key-store-password: server-store-pass
server.ssl.key-alias: server-keypair
server.ssl.key-password: server-key-pass