server.port: 8080
logging:
  level:
    ROOT: error
    io.reactivestax: debug
    org.springframework: error
    org.springframework.boot.context.config: debug
    org.springframework.security: TRACE
    org.springframework.web: error
pattern:
  console: "%d %-5level %logger : %msg%n"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: "https://dev-u14yaemx.us.auth0.com/"

