server:
  port: 9080
spring:
  kafka:
    properties:
      bootstrap.servers: localhost:29092
      schema.registry.url: http://localhost:8081
    consumer:
      group-id: my-microservice
      auto-offset-reset: latest
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor

#
#kafka:
#  bootstrap-servers: localhost:29092
#  topic:
#    name: order1
#    consumer-group: neworders-cg7